services:
  meshsense:
    build: .
    ports:
      - "5921:5921"
      - "5920:5920"
    environment:
      - PORT=5921
      - DEV_UI_URL=http://localhost:5921
    tty: true
    stdin_open: true
    privileged: true  # Run the container in privileged mode

